# db config
spring:
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 12MB
  mvc:
    static-path-pattern: /static/**
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.0.144:3306/team_h
    username: team_h
    password: green502

# mybatis config

mybatis:
  type-aliases-package: com.green.boardver99
  mapper-locations: mybatis/mapper/**/*.xml


# swagger
springdoc:
  swagger-ui:
    path: /swagger.html


file:
  dir: D:/download/
